version: '3.7'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MSQL_DATABASE: shoe-store
    ports:
      - 3307:3006
    networks:
      - shoe-store-network
    
  phpmyadmin8-container:
    #intel host
    image: phpmyadmin/phpmyadmin    
    #image: arm64v8/phpmyadmin #choose this if you are running on Mac Apple Silicon(M1, M2,...)
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container      
    ports:
      - "8100:80" #port mapping
    environment:
      PMA_HOST: mysql8-container #phpMyAdmin Host, PMA = PHP My Amin
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - shoe-store-network
  
  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - shoe-store-network

  shoe-store-container:
    container_name: shoe-store-container
    build:
      context: .
      dockerfile: DockerfileJavaSpring
    ports:
      - 8099:8088
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql8-container:3306/shoe-store?serverTimezone=UTC&allowPublicKeyRetrieval=true
      MYSQL_ROOT_PASSWORD: 123123
    depends_on:
      - mysql8-container
    networks:
      - shoe-store-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8088/api/v1/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s #20s after container created, health check

networks:
  shoe-store-network:
    name: shoe-store-network
    driver: bridge

